name = "veyla-ai"
compatibility_date = "2024-01-05"

[build]
command = "npm install && npm run build"
dist = "dist"

[site]
bucket = "./dist"

[env.production]
routes = [
  { pattern = "veylaai.com", custom_domain = true }
]

[build.environment]
NODE_ENV = "18"
NPM_VERSION = "9"
