name = "veyla-ai"
compatibility_date = "2024-01-05"

[build]
command = "npm install && npm run build"
cwd = "packages/dashboard"
dist = ".next"

[site]
bucket = "./packages/dashboard/.next"

[env.production]
routes = [
  { pattern = "veylaai.com", custom_domain = true }
]

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"
