name = "veyla-ai"
compatibility_date = "2024-01-05"

[build]
command = "npm install && npm run build"
dist = "packages/landing/out"

[site]
bucket = "./packages/landing/out"

[build.environment]
NODE_ENV = "production"
NODE_VERSION = "18"
NPM_VERSION = "9"
